net_arch:
  pi: [256, 128, 64]
  vf: [256, 128, 64]
activation_fn: tanh
learning_rate: 0.0003
n_steps: 2048
batch_size: 64
n_epochs: 10
gamma: 0.99
gae_lambda: 0.95
clip_range: 0.2
clip_range_vf: 0.2
ent_coef: 0.0
vf_coef: 0.5
max_grad_norm: 0.5
normalize_advantage: true